import {releaseStockSeries} from './release-stock.js';
import {RELEASE_VIEWS} from './ai-release-views.js';
import {datedEvents} from './event-timing.js';
import React,{useEffect,useMemo,useState} from 'react';
import {CalendarDays,Download} from 'lucide-react';
import {Field,ReelPreview,ExportModal} from './components.jsx';
import {useLanguages} from './language-context.js';
import {downloadBlob} from './data.js';
import {RELEASE_PUBLISHERS,RELEASE_CATEGORIES,selectReleases,releaseCount,releaseMonths,releaseCsv} from './ai-releases.js';
const defaults={start:'2026-07-01',end:'2026-09-30',publishers:['openai','anthropic'],categories:['general','coding','open-weight'],mode:'pulse',count:'versions',format:'9:16',duration:24,title:'',logos:true,stockEnabled:false,stockBasis:'split'};
function savedSettings(){try{const s=JSON.parse(localStorage.getItem('plotwist-ai-releases-v1'));if(!s)return defaults;return {...defaults,...s,publishers:RELEASE_PUBLISHERS.map(p=>p.id).filter(p=>s.publishers?.includes(p)),categories:RELEASE_CATEGORIES.filter(c=>s.categories?.includes(c)),mode:RELEASE_VIEWS.some(v=>v.id===s.mode)?s.mode:'pulse',count:s.count==='launches'?'launches':'versions',format:['9:16','4:5','1:1'].includes(s.format)?s.format:'9:16',duration:Math.max(6,Math.min(600,Number(s.duration)||24))};}catch{return defaults;}}
export default function AIReleaseStudio({fontId='arial'}){
 const {uiLanguage,reelLanguage}=useLanguages(),en=uiLanguage==='en',t=(pl,eng)=>en?eng:pl;
 const [settings,setSettings]=useState(savedSettings),[data,setData]=useState(null),[error,setError]=useState(''),[exporting,setExporting]=useState(false);
 const [stock,setStock]=useState(null),[stockError,setStockError]=useState(''),[stockRetry,setStockRetry]=useState(0);
 const set=(key,value)=>setSettings(s=>({...s,[key]:value}));
 useEffect(()=>{try{localStorage.setItem('plotwist-ai-releases-v1',JSON.stringify(settings));}catch{}},[settings]);
 useEffect(()=>{const c=new AbortController();fetch('/ai/releases.json',{signal:c.signal}).then(r=>{if(!r.ok)throw Error(String(r.status));return r.json();}).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>c.abort();},[]);
 useEffect(()=>{if(!settings.stockEnabled||stock)return;const c=new AbortController();setStockError('');fetch('/market/NVDA.json',{signal:c.signal}).then(r=>{if(!r.ok)throw Error(String(r.status));return r.json();}).then(setStock).catch(e=>{if(e.name!=='AbortError')setStockError(e.message);});return()=>c.abort();},[settings.stockEnabled,stock,stockRetry]);
 const stockSeries=useMemo(()=>settings.stockEnabled&&stock?releaseStockSeries(stock,settings.start,settings.end,settings.stockBasis):null,[stock,settings.stockEnabled,settings.start,settings.end,settings.stockBasis]);
 const rows=useMemo(()=>selectReleases(data?.rows||[],settings),[data,settings]);
 const valid=(!settings.stockEnabled||!!stockSeries?.points.length&&!stockError)&&!!data&&rows.length>0&&settings.start>=data.coverage.start&&settings.end<=data.coverage.end&&settings.start<=settings.end;
 const config=useMemo(()=>({format:settings.format,fontId,theme:'paper',title:settings.title||(reelLanguage==='en'?'The AI release calendar.':'Kalendarz premier AI.'),titleIsCustom:true,timelineEvents:datedEvents(rows,settings.start,settings.end),releases:{...settings,rows,stock:stockSeries,verifiedAt:data?.verifiedAt}}),[settings,rows,fontId,reelLanguage,data,stockSeries]);
 const categoryNames={general:t('Modele ogólne','General models'),coding:t('Modele programistyczne','Coding models'),'open-weight':t('Otwarte wagi','Open weights'),revision:t('Ogłoszone aktualizacje','Announced revisions'),restricted:t('Dostęp partnerski · bez premiery publicznej','Partner access · not publicly released')};
 const months=releaseMonths(rows,settings.start,settings.end,settings.count);
 function exportData(type){const payload={...data,selection:settings,rows,months,stock:stockSeries};downloadBlob(new Blob([type==='csv'?releaseCsv(rows):JSON.stringify(payload,null,2)],{type:type==='csv'?'text/csv;charset=utf-8':'application/json'}),`ai-releases-${settings.start}-${settings.end}.${type}`);}
 return <div className="ai-page ai-release-page">
  <div className="ai-heading"><div><span className="ai-eyebrow"><CalendarDays size={16}/>{t('KALENDARZ PREMIER AI','AI RELEASE CALENDAR')}</span><h1>{t('Kolejny model. Kolejna data.','Another model. Another date.')}</h1><p>{t('Zobacz rytm premier i przerwy między nimi.','See the rhythm of releases and the gaps between them.')}</p></div><button className="primary" disabled={!valid} onClick={()=>setExporting(true)}><Download size={17}/>{t('Eksportuj rolkę','Export reel')}</button></div>
  <div className="ai-counts"><span>{data?.rows.length??'…'} {t('pozycji w katalogu','catalogue entries')}</span><span>2018–2026 · {RELEASE_PUBLISHERS.length} {t('producentów','publishers')}</span><span>{t('Weryfikacja:','Verified:')} {data?.verifiedAt??'…'}</span></div>
  {error&&<p role="alert">{t('Nie udało się wczytać katalogu. Odśwież stronę.','Could not load the catalogue. Refresh the page.')} ({error})</p>}
  <div className="ai-workspace reel-workspace"><div className="reel-data-column"><section className="ai-controls" aria-label={t('Ustawienia premier AI','AI release settings')}>
   <Field label={t('Wariant rolki','Reel style')}><select aria-label={t('Wariant rolki','Reel style')} value={settings.mode} onChange={e=>set('mode',e.target.value)}>{RELEASE_VIEWS.map(v=><option key={v.id} value={v.id}>{t(v.pl,v.en)}</option>)}</select></Field>
   <p className="ai-description">{settings.mode==='cards'?t('Kolejne daty tworzą stos kart. Modele z tego samego dnia pokazujemy razem.','Each date creates a card. Models from the same day appear together.'):settings.mode==='heatmap'?t('Kolor i liczba pokazują premiery w miesiącu. Przy długim okresie mapa przesuwa okno czterech lat.','Colour and counts show monthly releases. Long periods use a rolling four-year window.'):settings.mode==='gaps'?t('Wysokość słupka to dni od poprzedniej daty premier w wybranym katalogu. Jednoczesne premiery nie tworzą zerowych odstępów.','Bar height is days since the previous release date in the selected catalogue. Simultaneous releases do not create zero-length gaps.'):null}</p>
   <div className="release-presets"><button className="secondary" onClick={()=>setSettings(s=>({...s,start:'2023-01-01',end:data?.coverage.end||'2026-09-30',publishers:RELEASE_PUBLISHERS.map(p=>p.id),categories:['general','coding','open-weight']}))}>{t('Wszyscy producenci','All publishers')}</button><button className="secondary" onClick={()=>setSettings(s=>({...s,start:'2023-03-21',end:'2026-09-30',publishers:['google'],categories:['general','coding','open-weight','restricted']}))}>{t('Google: Bard → Gemini 4','Google: Bard → Gemini 4')}</button><button className="secondary" onClick={()=>setSettings(s=>({...s,start:'2018-06-11',end:data?.coverage.end||'2026-09-30',publishers:['openai'],categories:['general','coding','open-weight']}))}>{t('OpenAI od GPT-1','OpenAI from GPT-1')}</button>{[['2026-09-01','2026-09-30',t('Wrzesień 2026','September 2026')],['2026-01-01','2026-09-30','2026'],['2024-01-01','2026-09-30','2024–2026']].map(([start,end,label])=><button className="secondary" key={start} onClick={()=>setSettings(s=>({...s,start,end}))}>{label}</button>)}</div>
   <Field label={t('Od dnia','From date')}><input type="date" aria-label={t('Od dnia','From date')} min={data?.coverage.start} max={data?.coverage.end} value={settings.start} onChange={e=>set('start',e.target.value)}/></Field>
   <Field label={t('Do dnia','To date')}><input type="date" aria-label={t('Do dnia','To date')} min={data?.coverage.start} max={data?.coverage.end} value={settings.end} onChange={e=>set('end',e.target.value)}/></Field>
   <fieldset className="release-checks"><legend>{t('Cena akcji na osi premier','Stock price alongside releases')}</legend>
    <label><input type="checkbox" checked={!!settings.stockEnabled} onChange={e=>set('stockEnabled',e.target.checked)}/>{t('Dodaj cenę NVIDIA (USD)','Add NVIDIA price (USD)')}</label>
    {settings.stockEnabled&&<>
     <Field label={t('Rodzaj ceny NVIDIA','NVIDIA price basis')}><select aria-label={t('Rodzaj ceny NVIDIA','NVIDIA price basis')} value={settings.stockBasis} onChange={e=>set('stockBasis',e.target.value)}><option value="split">{t('Zamknięcie po korekcie splitów','Split-adjusted close')}</option><option value="raw">{t('Cena nominalna · odtworzona','Nominal close · reconstructed')}</option></select></Field>
     <p className="ai-description">{t('Ten sam dzień i te same pauzy co premiery. W dni bez sesji używamy ostatniego zamknięcia. Wygląd linii, logo i wartości ustawisz w Wygląd → Wykres → Etykiety przy liniach.','Uses the release clock and pauses. Non-trading days use the previous close. Customize the line, logo and values in Appearance → Chart → Line labels.')}</p>
     {stock&&<p className="ai-description">Yahoo Finance · {stock.rows[0][0]} – {stock.rows.at(-1)[0]} · USD<br/>{t('Korekta splitów zapewnia porównywalność cen; cena nominalna jest odtworzona z tych korekt. Bez korekty dywidend.','Split adjustment keeps prices comparable; nominal prices are reconstructed from split ratios. Not dividend-adjusted.')}</p>}
     {!stock&&!stockError&&<p role="status">{t('Wczytuję notowania NVIDIA…','Loading NVIDIA quotes…')}</p>}
     {stockError&&<p role="alert">{t('Nie udało się wczytać notowań.','Could not load quotes.')} <button type="button" onClick={()=>setStockRetry(n=>n+1)}>{t('Spróbuj ponownie','Retry')}</button></p>}
     {stock&&settings.end>stock.rows.at(-1)[0]&&<p role="status">{t('Premiery sięgają dalej niż dostępne ceny. Linia zatrzyma się na ostatnim notowaniu z datą: ','Releases extend beyond price coverage. The line stops at its last quote dated: ')}{stock.rows.at(-1)[0]}.</p>}
    </>}
   </fieldset>
   <fieldset className="release-checks"><legend>{t('Producenci','Publishers')}</legend>{RELEASE_PUBLISHERS.map(p=><label key={p.id}><input type="checkbox" checked={settings.publishers.includes(p.id)} onChange={e=>set('publishers',e.target.checked?[...settings.publishers,p.id]:settings.publishers.filter(id=>id!==p.id))}/><i style={{background:p.color}}/><span>{p.name}<small className="release-family">{p.family}</small></span></label>)}</fieldset>
   <fieldset className="release-checks"><legend>{t('Zakres katalogu','Catalogue scope')}</legend>{RELEASE_CATEGORIES.map(c=><label key={c}><input type="checkbox" checked={settings.categories.includes(c)} onChange={e=>set('categories',e.target.checked?[...settings.categories,c]:settings.categories.filter(id=>id!==c))}/>{categoryNames[c]}</label>)}</fieldset>
   <Field label={t('Co liczymy','Counting unit')}><select aria-label={t('Co liczymy','Counting unit')} value={settings.count} onChange={e=>set('count',e.target.value)}><option value="versions">{t('Nazwane wersje w katalogu','Named versions in catalogue')}</option><option value="launches">{t('Premiery · producent + dzień','Launches · publisher + day')}</option></select></Field>
   <p className="ai-description">{t('Wspólna premiera trzech modeli to trzy wersje albo jedno wydarzenie producenta. Odstęp liczymy między różnymi datami w wybranym filtrze.','Three models launched together count as three versions or one publisher event. Gaps use distinct dates in the current selection.')}</p>
   <Field label={t('Format rolki','Reel format')}><select aria-label={t('Format rolki','Reel format')} value={settings.format} onChange={e=>set('format',e.target.value)}>{['9:16','4:5','1:1'].map(f=><option key={f}>{f}</option>)}</select></Field>
   <Field label={t('Długość (sekundy)','Duration (seconds)')}><input type="number" aria-label={t('Długość (sekundy)','Duration (seconds)')} min="6" max="600" value={settings.duration} onChange={e=>set('duration',Math.max(6,Math.min(600,Number(e.target.value)||6)))}/></Field>
   <Field label={t('Własny tytuł','Custom title')}><input aria-label={t('Własny tytuł','Custom title')} placeholder={t('Kalendarz premier AI.','The AI release calendar.')} value={settings.title} maxLength="160" onChange={e=>set('title',e.target.value)}/></Field>
   <label className="ai-brand-toggle"><input type="checkbox" checked={settings.logos} onChange={e=>set('logos',e.target.checked)}/>{t('Logo producentów','Publisher logos')}</label>
   {rows.some(r=>r.category==='restricted')&&<p className="ai-description" role="status">{t('Wybrany zakres obejmuje dostęp partnerski (np. Gemini 4 Argon), a nie wyłącznie publiczne premiery. Oznaczenie pojawi się również na rolce.','This selection includes partner-only access (e.g. Gemini 4 Argon), not only public releases. The reel will identify these events too.')}</p>}<p className="ai-description">{valid?`${releaseCount(rows,settings.count)} ${t('w wybranym zakresie. Pauzy przy premierach ustawisz w Wygląd → Animacje.','in the selected range. Set pauses at releases in Appearance → Animations.')}`:t('Wybierz producenta, kategorię i zakres dat z katalogu (2018-06-11 – 2026-09-30).','Select a publisher, category and dates within the catalogue (2018-06-11 – 2026-09-30).')}</p>
  </section></div><ReelPreview config={config} duration={settings.duration} valid={valid} onDurationChange={duration=>set('duration',duration)}/></div>
  <div className="ai-method-note"><strong>{t('Co oznacza licznik','What the counter means')}</strong><p>{data?.methodology[uiLanguage]}</p><p>{data?.exclusions[uiLanguage]}</p><p>{t('Tempo nie musi rosnąć w każdym miesiącu. Przy szerokim zakresie wydłuż rolkę lub wybierz jeden kwartał, aby dało się przeczytać nazwy. Dane nie aktualizują się automatycznie.','The pace does not necessarily rise every month. For a wide date range, use a longer reel or choose one quarter so viewers can read names. Data is not updated automatically.')}</p></div>
  <section className="ai-results"><div className="ai-table-heading"><div><h2>{t('Daty, które stoją za rolką','The dates behind the reel')}</h2><p>{t('Chronologicznie · każda pozycja ma źródło producenta','Chronological · each entry links to its publisher')}</p></div><div><button className="secondary" disabled={!rows.length} onClick={()=>exportData('csv')}>CSV</button><button className="secondary" disabled={!rows.length} onClick={()=>exportData('json')}>{t('JSON + metodologia','JSON + methodology')}</button></div></div><div className="ai-table-scroll"><table><thead><tr><th>{t('Data','Date')}</th><th>{t('Model','Model')}</th><th>{t('Kategoria','Category')}</th><th>{t('Źródło','Source')}</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.date}</td><th scope="row">{r.name}<small>{RELEASE_PUBLISHERS.find(p=>p.id===r.publisher).name}</small></th><td>{categoryNames[r.category]}</td><td><a href={r.sourceUrl} target="_blank" rel="noreferrer">{t('Komunikat producenta ↗','Publisher notice ↗')}</a>{r.notes&&<details><summary>{t('Uwagi weryfikacyjne (EN)','Verification notes')}</summary><p>{r.notes}</p></details>}</td></tr>)}</tbody></table></div></section>
  {exporting&&<ExportModal config={config} duration={settings.duration} onClose={()=>setExporting(false)}/>}
 </div>;
}
