import {useProjectSeed,useProjectState,useProjectDraft,useProjects} from './Projects.jsx';
import {useLanguages,localeFor} from './language-context.js';
import {translate} from './translations.js';
import {PresentationPicker} from './Presentation.jsx';
import React,{useEffect,useMemo,useState} from 'react';
import {ArrowUpRight,BrainCircuit,Download,Info,Search} from 'lucide-react';
import {ExportModal,Field,ReelPreview} from './components.jsx';
import {downloadBlob} from './data.js';
import {marketCsv} from './market.js';
import {aiDate,aiValue as formatAiValue,rankAt,selectAiRows,timelineSelection} from './ai.js';
import {annotateAiBrands,aiBrandOptions,defaultAiBrands,aiBrandRuleVersion} from './ai-brands.js';
import {buildAiBrandHistory,brandLatestNote,brandRecordNote,aiModelLabel} from './ai-brand-history.js';
import {preloadReelAssets} from './reel-assets.js';
import './ai.css';
import AIReleaseStudio from './AIReleaseStudio.jsx';
const json=async(path,signal)=>{const r=await fetch(path,{signal});if(!r.ok)throw new Error('Nie udało się wczytać danych benchmarku. Odśwież stronę.');return r.json();};
const safeUrl=url=>/^https:\/\//.test(url||'')?url:undefined;
function TrackingInfo({data,onChoose}){
 const average=data.aggregation==='tracking-last-n';
 return <div className="ai-method-note">
  <strong>{average?'Średnia z prób · jak w TrackingAI':'Pojedyncze próby · historia TrackingAI'}</strong>
  <p>{average?'Średnia obejmuje ostatnie maks. 7 prób każdego aliasu, nie 7 dni. Jeśli prób jest mniej, używamy wszystkich dostępnych. Rekord i ostatnia próba mogą mieć inne wartości.':'Tu każda obserwacja to jeden test. Wyścig rankingu pokazuje ostatnią próbę, a Schody rekordów — rekord. Wykres na stronie TrackingAI pokazuje średnią z ostatnich maks. 7 prób.'}</p>
  {average&&<p>Aktualne nazwy pochodzą z konfiguracji TrackingAI. Ten sam alias mógł wcześniej wskazywać inną wersję modelu. Tego rankingu nie należy traktować jako wyników z dnia premiery.</p>}
  <small>Ostatnia kontrola źródła: {data.checkedAt?.replace('T',' ').replace(/\.\d+Z$/,' UTC')}</small>
  {average?<div className="market-source-links"><button type="button" className="text-btn" onClick={()=>onChoose(`iq-${data.trackingTest}`)}>Pojedyncze próby · tekst</button><button type="button" className="text-btn" onClick={()=>onChoose(`iq-${data.trackingTest}-vision`)}>Pojedyncze próby · Vision</button></div>:<button type="button" className="secondary" onClick={()=>onChoose(`tracking-${data.trackingTest}-ranking`)}>Otwórz ranking jak w TrackingAI</button>}
 </div>;
}
export default function AIStudio(props){
 const project=useProjects();const [section,setSection]=useState(project?.seed?.kind==='releases'?'releases':'benchmarks');const {uiLanguage}=useLanguages();const en=uiLanguage==='en';
 return <><nav className="ai-section-switch" aria-label={en?'AI studio section':'Sekcja studia AI'}><button className={section==='benchmarks'?'selected':''} aria-pressed={section==='benchmarks'} onClick={()=>setSection('benchmarks')}>{en?'Benchmarks':'Benchmarki'}</button><button className={section==='releases'?'selected':''} aria-pressed={section==='releases'} onClick={()=>setSection('releases')}>{en?'Model releases':'Premiery modeli'}</button></nav>{section==='releases'?<AIReleaseStudio {...props}/>:<AIBenchmarkStudio {...props}/>}</>;
}
function AIBenchmarkStudio({fontId='arial',onFontChange}){
 const initial=useProjectSeed('ai');
 const {uiLanguage,reelLanguage}=useLanguages();const aiValue=value=>formatAiValue(value,uiLanguage,data?.scoreDecimals??1);
 const [titleIsCustom,setTitleIsCustom]=useProjectState(initial,'titleIsCustom',false);
 const [format,setFormat]=useProjectState(initial,'format',()=>{try{const saved=localStorage.getItem('plotwist-ai-format-v1');return ['9:16','4:5','1:1'].includes(saved)?saved:'9:16';}catch{return '9:16';}});
 useEffect(()=>{try{localStorage.setItem('plotwist-ai-format-v1',format);}catch{}},[format]);
 const [groupBy,setGroupBy]=useProjectState(initial,'groupBy','model'),[selectedBrands,setSelectedBrands]=useProjectState(initial,'selectedBrands',[]),[brandMethod,setBrandMethod]=useProjectState(initial,'brandMethod','latest'),[brandSearch,setBrandSearch]=useState('');
 const [showBrandLogos,setShowBrandLogos]=useProjectState(initial,'showBrandLogos',true),[showLeaderNames,setShowLeaderNames]=useProjectState(initial,'showLeaderNames',true),[assetsReady,setAssetsReady]=useState(false),[assetError,setAssetError]=useState('');
 const [manifest,setManifest]=useProjectState(initial,'manifest',null),[data,setData]=useProjectState(initial,'data',null),[id,setId]=useProjectState(initial,'id','eci'),[error,setError]=useState('');
 const [basis,setBasis]=useProjectState(initial,'basis','release'),[start,setStart]=useProjectState(initial,'start',''),[end,setEnd]=useProjectState(initial,'end',''),[query,setQuery]=useProjectState(initial,'query',''),[organization,setOrganization]=useProjectState(initial,'organization',''),[protocol,setProtocol]=useProjectState(initial,'protocol','');
 const [mode,setMode]=useProjectState(initial,'mode','timeline'),[duration,setDuration]=useProjectState(initial,'duration',20),[theme,setTheme]=useProjectState(initial,'theme','dark'),[title,setTitle]=useProjectState(initial,'title','Jak szybko rozwija się AI?'),[comparison,setComparison]=useProjectState(initial,'comparison',''),[page,setPage]=useState(0),[exporting,setExporting]=useState(false);
 useProjectDraft('ai',{titleIsCustom,format,groupBy,selectedBrands,brandMethod,showBrandLogos,showLeaderNames,manifest,data,id,basis,start,end,query,organization,protocol,mode,duration,theme,title,comparison},true);
 useEffect(()=>{if(initial?.manifest)return;const c=new AbortController();json('/ai/manifest.json',c.signal).then(setManifest).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>c.abort();},[]);
 useEffect(()=>{if(initial?.data&&id===initial.id){setData(initial.data);return;}const c=new AbortController();setData(null);setError('');json(`/ai/${id}.json`,c.signal).then(d=>{setData(d);setTitleIsCustom(false);setBasis(d.defaultBasis);setStart('');setEnd('');setQuery('');setOrganization('');setProtocol(id==='gpqa'?'Prompt od 20.02.2026':'');setComparison('');setMode(d.defaultMode||(id==='codeforces2024'?'duel':'timeline'));setTitle(id.startsWith('tracking-')?d.name:id==='eci'?'Jak szybko rozwija się AI?':id.startsWith('iq-')?'Jak modele rozwiązują test „IQ”?':id==='codeforces2024'?'AI na zawodach programistycznych.':`${d.name}. Kolejne modele.`);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>c.abort();},[id]);
 const protocols=useMemo(()=>[...new Set(data?.rows.map(r=>r.protocol)||[])].sort(),[data]);
 const orgs=useMemo(()=>[...new Set(data?.rows.map(r=>r.organization).filter(Boolean)||[])].sort(),[data]);
 const hasObserved=!!data?.rows.some(r=>r.observedAt),hasRelease=!!data?.rows.some(r=>r.releaseDate);
 const annotated=useMemo(()=>annotateAiBrands(data?.rows||[]),[data]);
 const brandOptions=useMemo(()=>aiBrandOptions(annotated),[annotated]);
 useEffect(()=>{if(!data)return;setSelectedBrands(old=>{const available=old.filter(id=>brandOptions.some(b=>b.id===id));return available.length?available:defaultAiBrands(annotated);});},[data,brandOptions,annotated]);
 const sourceRows=useMemo(()=>data?selectAiRows(annotated,{basis,start:groupBy==='brand'?'':start,end:end||'9999',organization:groupBy==='brand'?'':organization,query,protocol,separateProtocols:groupBy==='brand'}):[],[data,annotated,basis,start,end,organization,query,protocol,groupBy]);
 const brandRows=useMemo(()=>sourceRows.filter(r=>selectedBrands.includes(r.brandId)),[sourceRows,selectedBrands]);
 const rows=useMemo(()=>groupBy==='brand'?brandRows.filter(r=>!start||r.date>=start):sourceRows,[sourceRows,brandRows,groupBy,start]);
 const historyEnd=sourceRows.at(-1)?.date||end;
 const history=useMemo(()=>buildAiBrandHistory(brandRows,{brandIds:selectedBrands,start,end:historyEnd,method:brandMethod}),[brandRows,selectedBrands,start,historyEnd,brandMethod]);
 const chosenBrands=useMemo(()=>selectedBrands.map(id=>brandOptions.find(b=>b.id===id)).filter(Boolean),[selectedBrands,brandOptions]);
 const unassigned=annotated.filter(r=>!r.brandId).length;
 const timeline=useMemo(()=>timelineSelection(rows),[rows]);
 const ranked=useMemo(()=>rankAt(rows,rows.at(-1)?.date||''),[rows]);
 const chosen=ranked.find(r=>r.modelId===comparison)||ranked[0];
 const chartRows=groupBy==='brand'?brandRows:mode==='timeline'?timeline:rows;
 const scope=[groupBy==='brand'?'Porównanie marek':organization,query?`Filtr: ${query}`:'',protocol].filter(Boolean).join(' · ');
 const config=useMemo(()=>({format,title,titleIsCustom,theme,fontId,ai:{rows:chartRows,benchmark:data,basis,mode,scope,comparison:chosen?.modelId,groupBy,history,brands:chosenBrands,showBrandLogos,showLeaderNames}}),[format,chartRows,data,basis,mode,title,titleIsCustom,theme,fontId,scope,chosen?.modelId,groupBy,history,chosenBrands,showBrandLogos,showLeaderNames]);
 useEffect(()=>{let active=true;setAssetsReady(false);setAssetError('');preloadReelAssets(config).then(()=>{if(active)setAssetsReady(true);}).catch(e=>{if(active)setAssetError(e.message);});return()=>{active=false;};},[config]);
 const hasResults=groupBy==='brand'?history.frames.some(f=>f.leaders.length):rows.length>0;
 const valid=!!data&&hasResults&&assetsReady&&(!start||!end||start<=end)&&(groupBy==='brand'||mode!=='duel'||!!data.baseline);
 useEffect(()=>{if(groupBy==='brand'&&!['records','ranking','timeline'].includes(mode))setMode('records');},[groupBy,mode]);
 const missingDates=data?.rows.filter(r=>!aiDate(r,basis)).length||0;
 const latest=data?.rows.map(r=>r.lastRunAt?.slice(0,10)||r.observedAt?.slice(0,10)||r.releaseDate).filter(Boolean).sort().at(-1);
 const pageRows=(data?.aggregation==='tracking-last-n'?rows.toSorted((a,b)=>b.score-a.score||a.model.localeCompare(b.model)):rows.toReversed()).slice(page*20,page*20+20),pages=Math.max(1,Math.ceil(rows.length/20));
 useEffect(()=>setPage(0),[rows]);
 function exportData(type){
   if(type==='csv'&&groupBy==='brand'){
    const records=history.frames.flatMap(frame=>frame.leaders.map(l=>[frame.date,l.brand.id,l.brand.publisher,l.winner.model,l.winner.modelId,l.score,l.winner.date,l.winner.releaseDate||'',l.winner.observedAt||'',l.winner.dateKind||'',l.winner.effort||'',l.winner.protocol,l.winner.sourceUrl]));
    downloadBlob(new Blob([marketCsv(records,['frame_date','brand_id','publisher','model','model_id','score','source_date','release_date','observed_at','date_kind','effort','protocol','source_url'])],{type:'text/csv;charset=utf-8'}),`plotwist-ai-${id}-marki.csv`);return;
   }
   if(type==='csv'){
     const headers=['id','model','modelId','organization','brandId','brandMethod','date','releaseDate','observedAt','dateKind','effort','score','sourceValue','stderr','low','high','rawScore','validScore','total','elo','protocol','sourceUrl','notes',...(data.id.startsWith('arc3')?['harness','sourceModelId','sourceReleaseDate','releaseDateSourceUrl','evaluationCostUsd']:[])];
     if(data.aggregation==='tracking-last-n')headers.push('sourceAlias','sampleCount','windowLimit','latestScore','recordScore','lastRunAt','firstRunInAverage','modality','modelVersionUnverified','runs');
     downloadBlob(new Blob([marketCsv(rows.map(r=>headers.map(h=>h==='runs'?JSON.stringify(r.runs):r[h]??'')),headers)],{type:'text/csv;charset=utf-8'}),`plotwist-ai-${id}.csv`);
   } else downloadBlob(new Blob([JSON.stringify({benchmark:{...data,rows:undefined},selection:{format,basis,start,end,organization,query,protocol,mode,groupBy,selectedBrands,brandMethod,showBrandLogos,showLeaderNames},brandRules:aiBrandRuleVersion,storyIds:chartRows.map(r=>r.id),rows,contextRows:groupBy==='brand'?brandRows.filter(r=>start&&r.date<start):undefined,brandHistory:groupBy==='brand'?history:undefined},null,2)],{type:'application/json'}),`plotwist-ai-${id}-zrodla.json`);
 }
 return <div className="ai-page">
   <div className="ai-heading"><div><span className="ai-eyebrow"><BrainCircuit size={16}/> ARCHIWUM MOŻLIWOŚCI AI</span><h1>Każdy model ma swój moment.</h1><p>Znajdź przełom. Wybierz formę. Opowiedz historię.</p></div><button className="primary" disabled={!valid} onClick={()=>setExporting(true)}><Download size={17}/>Eksportuj rolkę</button></div>
   <div className="ai-counts"><span>{manifest?.benchmarks.length||'…'} zestawów i wersji testów</span><span>{manifest?.totalObservations.toLocaleString(localeFor(uiLanguage))||'…'} pomiarów</span><span>Dane pobrane: {manifest?.retrievedAt||'…'}</span></div>
   {manifest?.featuredRelease&&<div className="ai-release-update"><div><strong><span>Nowe wyniki:</span> <span translate="no">{manifest.featuredRelease.model}</span></strong><p translate="no">{manifest.featuredRelease.summary?.[uiLanguage]||manifest.featuredRelease.summary?.pl}</p></div><button className="secondary" onClick={()=>{setId(manifest.featuredRelease.benchmarkId);setGroupBy('model');setQuery('');setStart('');setEnd('');setOrganization('');setProtocol('');setMode('ranking');}}>Pokaż nowe wyniki</button></div>}
   <div className="ai-workspace reel-workspace"><div className="reel-data-column">
     <section className="ai-controls" aria-label="Ustawienia benchmarków AI">
       <Field label="Grupowanie wyników"><select aria-label="Grupowanie wyników" value={groupBy} onChange={e=>{const value=e.target.value;setGroupBy(value);if(value==='brand'&&!['records','ranking','timeline'].includes(mode))setMode('records');else if(value==='brand'&&mode==='timeline')setMode('records');}}><option value="model">Pojedyncze modele</option><option value="brand">Najlepsze modele według marki</option></select></Field>
       {groupBy==='brand'&&<div className="ai-brand-controls">
        <fieldset className="ai-brand-fieldset"><legend>Śledzone marki · maks. 6</legend><input type="search" aria-label="Szukaj marki AI" placeholder="Szukaj marki lub producenta…" value={brandSearch} onChange={e=>setBrandSearch(e.target.value)}/><div className="ai-brand-options">{brandOptions.filter(b=>`${b.label} ${b.publisher}`.toLowerCase().includes(brandSearch.toLowerCase())).map(brand=><label key={brand.id}><input type="checkbox" aria-label={brand.label} checked={selectedBrands.includes(brand.id)} disabled={!selectedBrands.includes(brand.id)&&selectedBrands.length>=6} onChange={e=>setSelectedBrands(old=>e.target.checked?[...old,brand.id]:old.filter(id=>id!==brand.id))}/>{brand.logo&&<img src={brand.logo} alt=""/>}<span translate="no"><strong>{brand.name}</strong><small>{brand.publisher}</small></span><i style={{background:brand.color}}/></label>)}</div><small>{selectedBrands.length}/6 <span>wybranych marek</span></small><button className="text-btn" onClick={()=>setSelectedBrands([])}>Wyczyść marki</button></fieldset>
        <Field label="Wynik reprezentujący markę"><select aria-label="Wynik reprezentujący markę" value={brandMethod} onChange={e=>setBrandMethod(e.target.value)}><option value="latest">Najlepszy z ostatnich wyników</option><option value="record">Rekord historyczny marki</option></select></Field>
        <label className="ai-brand-toggle"><input type="checkbox" checked={showBrandLogos} onChange={e=>setShowBrandLogos(e.target.checked)}/>Logo marki na rolce</label>
        <label className="ai-brand-toggle"><input type="checkbox" checked={showLeaderNames} onChange={e=>setShowLeaderNames(e.target.checked)}/>Nazwa prowadzącego modelu</label>
        {!selectedBrands.length&&<p role="status" className="ai-hint">Wybierz przynajmniej jedną markę.</p>}
       </div>}
       <PresentationPicker config={config} family="ai" value={mode} onChange={setMode} hasBaseline={!!data?.baseline}/><Field label="Benchmark"><select value={id} onChange={e=>setId(e.target.value)}>{manifest?.benchmarks.map(b=><option key={b.id} value={b.id}>{b.name}</option>)||<option value="eci">ECI · indeks możliwości</option>}</select></Field>
       {data&&<div className="ai-description"><span className="tag ready">{data.category}</span><p>{data.description}</p><a href={safeUrl(data.sourceUrl)} target="_blank" rel="noreferrer">Metodologia źródła<ArrowUpRight size={13}/></a></div>}
       {data?.trackingTest&&<TrackingInfo data={data} onChoose={setId}/>}
       <Field label="Co oznacza data?"><select value={basis} onChange={e=>{setBasis(e.target.value);setStart('');setEnd('');}}><option value="release" disabled={!hasRelease}>Premiera modelu · retrospektywa</option><option value="observed" disabled={!hasObserved}>{data?.dateKind==='snapshot'?'Data pobrania rankingu':'Data testu / publikacji wyniku'}</option></select></Field>
       <div className="field-pair"><Field label="Od dnia"><input type="date" aria-label="Początek historii AI" value={start} onInput={e=>setStart(e.target.value)}/></Field><Field label="Do dnia"><input type="date" aria-label="Koniec historii AI" value={end} onInput={e=>setEnd(e.target.value)}/></Field></div>
       <small className="ai-hint">Puste daty = cała dostępna historia.</small>
       {protocols.length>1&&<Field label="Protokół / źródło"><select value={protocol} onChange={e=>setProtocol(e.target.value)}><option value="">Wszystkie · porównanie orientacyjne</option>{protocols.map(p=><option key={p}>{p}</option>)}</select></Field>}
       {groupBy==='model'&&orgs.length>1&&<Field label="Organizacja"><select value={organization} onChange={e=>setOrganization(e.target.value)}><option value="">Wszystkie organizacje</option>{orgs.map(o=><option key={o}>{o}</option>)}</select></Field>}
       <div className="search-field ai-search"><Search size={17}/><input aria-label="Filtr modeli AI" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Filtruj, np. GPT, Claude, Gemini…"/></div>
       <Field label="Tytuł rolki"><textarea maxLength="75" rows="2" value={titleIsCustom?title:translate(title,reelLanguage)} onChange={e=>{setTitleIsCustom(true);setTitle(e.target.value);}}/>{titleIsCustom&&<button type="button" className="text-btn" onClick={()=>{setTitleIsCustom(false);setTitle(id.startsWith('tracking-')?data.name:id==='eci'?'Jak szybko rozwija się AI?':id.startsWith('iq-')?'Jak modele rozwiązują test „IQ”?':id==='codeforces2024'?'AI na zawodach programistycznych.':`${data?.name||''}. Kolejne modele.`);}}>Przywróć tytuł automatyczny</button>}</Field>
       <div className="field-pair"><Field label="Format wideo"><select aria-label="Format wideo" value={format} onChange={e=>setFormat(e.target.value)}>{['9:16','4:5','1:1'].map(f=><option key={f} value={f}>{f}</option>)}</select></Field><Field label="Długość rolki AI"><select value={duration} onChange={e=>setDuration(Number(e.target.value))}>{[6,12,20,30].map(d=><option key={d} value={d}>{d} s</option>)}</select></Field></div>
       {(error||assetError)&&<p role="alert" className="error">{error||assetError}</p>}{!data&&!error&&<p role="status">Wczytywanie wyników…</p>}{data&&!hasResults&&<p role="status" className="error">Brak pomiarów dla tego filtra. Zmień daty, nazwę lub protokół.</p>}
     </section>

     <aside className="ai-story-controls">
       <h2>O wybranej historii</h2>

       {groupBy==='brand'&&<div className="ai-brand-summary"><h3>Najlepsze modele na końcu zakresu</h3>{chosenBrands.map(brand=>{const leader=history.frames.at(-1)?.leaders.find(l=>l.brand.id===brand.id);return <div key={brand.id} style={{borderLeftColor:brand.color}}><strong translate="no">{brand.name} · {leader?`${aiValue(leader.score)} ${data?.unit}`:'—'}</strong><span translate="no">{aiModelLabel(leader?.winner)}</span>{!leader&&<small>Brak wyniku do tej daty</small>}{leader&&<small>{leader.winner.date} · {leader.winner.protocol}</small>}</div>})}<p>{brandMethod==='record'?brandRecordNote:brandLatestNote}</p><p>Wcześniejszy wynik może pozostać liderem na początku wybranego okresu. Brak pomiaru nie oznacza zera. Remisy rozstrzyga nazwa wariantu.</p>{new Set(brandRows.map(r=>r.protocol)).size>1&&<p className="ai-brand-warning">Wybrano różne protokoły. Porównanie jest orientacyjne; zawęź protokół, jeśli chcesz porównać te same warunki.</p>}</div>}
       {groupBy==='model'&&mode==='duel'&&data?.baseline&&<Field label="Model do porównania"><select value={chosen?.modelId||''} onChange={e=>setComparison(e.target.value)}>{ranked.map(r=><option key={r.modelId} value={r.modelId}>{r.model} · {aiValue(r.score)} {data.unit}</option>)}</select></Field>}
       <div className="ai-selection"><strong>{rows.length.toLocaleString(localeFor(uiLanguage))} pomiarów w filtrze</strong><p>{groupBy==='brand'?'Kolor i logo identyfikują markę. Etykieta modelu wskazuje wariant reprezentujący ją w danej chwili. Pełne nazwy konfiguracji i niepewność wyników znajdziesz w tabeli.':mode==='timeline'?`${timeline.length} kart wybranych z kolejnych rekordów w filtrze (maks. 8). Każda karta ma rzeczywistą datę i wartość.`:mode==='ranking'?'Ranking bierze ostatni odnotowany wynik wariantu, nie jego najlepszy wynik. Model pozostaje w rankingu do kolejnego pomiaru.':mode==='records'?'Schody pokazują najwyższy dotąd wynik w tym filtrze. Pomiary różnych modeli nie tworzą ciągłej trajektorii jednego modelu.':mode==='duel'?'Porównanie ostatniego wyniku wybranego modelu z opisanym punktem odniesienia.':'Punkty pojawiają się zgodnie z wybraną osią dat. Puste okresy nie są uzupełniane.'}</p></div>
       <div className="ai-context"><Info size={18}/><p>{basis==='release'?'To retrospektywa wg premier. Wynik mógł zostać zmierzony później; nie pokazujemy stanu wiedzy z dnia premiery.':data?.dateKind==='snapshot'?'To stan rankingu na dzień pobrania. Źródło nie podaje dat poszczególnych testów.':'To daty testów lub publikacji podane przez źródło. Brak daty pomiaru nie jest zastępowany datą premiery.'}</p></div>
     </aside></div>
     <ReelPreview config={config} duration={duration} valid={valid}/>
   </div>
   {data&&<>
     <div className="ai-method-note"><strong>{(data.trackingTest||data.id.startsWith('iq-'))?'„IQ” w cudzysłowie.':data.id==='eci'?'ECI to umowny indeks możliwości.':'Warunki testu mają znaczenie.'}</strong><p>{data.caveat}</p>{data.baseline&&<p><strong>Punkt odniesienia:</strong> {data.baseline.name} · {aiValue(data.baseline.score)} {data.baseline.unit}. {data.baseline.note} <a href={safeUrl(data.baseline.sourceUrl)} target="_blank" rel="noreferrer">Źródło</a></p>}</div>
     <section className="ai-results" aria-label="Tabela wyników benchmarków"><div className="ai-table-heading"><div><h2>Wyniki, które stoją za rolką.</h2><p>{data.name} · {data.unit} · {missingDates>0?`${missingDates} rekordów bez wybranego rodzaju daty pominięto.`:'Każdy wynik ma odsyłacz do źródła.'}</p></div><div><button className="secondary" disabled={!hasResults} onClick={()=>exportData('csv')}><Download size={16}/>CSV</button><button className="secondary" disabled={!hasResults} onClick={()=>exportData('json')}><Download size={16}/>Dane i metodologia</button></div></div>
       <div className="ai-table-scroll"><table><thead><tr><th>Model / konfiguracja</th><th>{data.aggregation==='tracking-last-n'?'Średnia TrackingAI':'Wynik'}</th><th>Premiera</th><th>{data.dateKind==='snapshot'?'Data pobrania rankingu':'Test / publikacja'}</th><th>Źródło i warunki</th></tr></thead><tbody>{pageRows.map(r=><tr key={r.id}><th scope="row" translate="no">{r.model}<small translate="no">{r.brand?.label||translate('Producent nieustalony',uiLanguage)}</small><small translate="no">{r.organization}</small><small translate="no">{r.modelId!==r.model?r.modelId:''}</small></th><td><strong>{aiValue(r.score)} {data.unit}</strong>{r.sampleCount!=null&&<><small>{translate(`Próby w średniej: ${r.sampleCount} / ${r.windowLimit}`,uiLanguage)}</small><small>{translate(`Ostatnia próba: ${r.latestScore} · rekord aliasu: ${r.recordScore}`,uiLanguage)}</small><small>{translate(`Ostatni test: ${r.lastRunAt.slice(0,10)}`,uiLanguage)}</small></>}{r.low!=null&&<small>90% CI: {aiValue(r.low)}–{aiValue(r.high)}</small>}{r.stderr!=null&&<small>SE: ±{aiValue(r.stderr)} p.p.</small>}{r.rawScore!=null&&<small>Surowe: {r.rawScore}/{r.total} · valid: {r.validScore}</small>}</td><td>{r.releaseDate||'Nie podano'}</td><td>{r.observedAt?.slice(0,10)||'Nie podano'}</td><td><a href={safeUrl(r.sourceUrl)} target="_blank" rel="noreferrer">Otwórz źródło<ArrowUpRight size={12}/></a><small>{r.protocol}</small>{r.runs&&<details><summary>Próby w średniej</summary>{r.runs.map(run=><p key={run.id}>{run.date.replace('T',' ')} · {aiValue(run.score)} {data.unit}</p>)}</details>}{r.notes&&<details><summary>Notatka źródła</summary><p translate="no">{r.notes}</p></details>}</td></tr>)}</tbody></table></div>
       <div className="pagination"><span>Strona {Math.min(page+1,pages)} z {pages} · {data.aggregation==='tracking-last-n'?'najwyższe wyniki najpierw':'najnowsze daty najpierw'}</span><div><button className="secondary" disabled={page===0} onClick={()=>setPage(p=>p-1)}>Poprzednia</button><button className="secondary" disabled={page+1>=pages} onClick={()=>setPage(p=>p+1)}>Następna</button></div></div>
     </section>
     <details className="ai-provenance"><summary>Przypisanie modeli do marek i źródła logo</summary><p>Najpierw używamy organizacji wskazanej przez źródło. Łączymy aliasy producentów, np. Google i Google DeepMind. Gdy organizacji brakuje, korzystamy z jawnych reguł nazw rodzin modeli. Zachowujemy oryginalną nazwę i organizację w danych.</p><p>DeepSeek Distill pozostaje przy DeepSeek, a dostrojenia innych zespołów przy ich wydawcy. Sama nazwa modelu bazowego nie określa wydawcy. Bing, Perplexity i Manus są oddzielnymi usługami; ich nazwy nie potwierdzają konkretnego modelu bazowego.</p><p>{unassigned} <span>pomiarów bez pewnego przypisania marki w tym benchmarku. Są dostępne jako pojedyncze modele, ale nie tworzą fikcyjnej wspólnej marki.</span></p><p>Logo są lokalnymi plikami z kolekcji Lobe Icons (MIT). Prawa do znaków pozostają przy właścicielach. Dla marek bez pliku logo używamy nazwy i koloru.</p><div className="market-source-links"><a href="/ai/brand-audit.json" target="_blank" rel="noreferrer">Spis przypisań modeli do marek</a><a href="/logos/ai/manifest.json" target="_blank" rel="noreferrer">Źródła logo AI</a></div></details>
     <details className="ai-provenance"><summary>Pochodzenie danych, aktualizacja i ograniczenia</summary><p>Snapshot pobrano {data.retrievedAt}. Najpóźniejsza data w źródle: {latest}. Zbiory nie aktualizują się automatycznie. Historia oznacza wyniki starszych modeli i archiwalne testy, nie komplet dawnych wersji leaderboardów.</p><p>W osi premier stosujemy ostatni pomiar danego wariantu dostępny w snapshotcie. Nie wybieramy najlepszego przebiegu. Braków danych nie zamieniamy na zera. Nazwy wariantów i budżety rozumowania pozostają rozdzielone. Nie wyliczamy średniej z różnych benchmarków.</p>{data.formula&&data.aggregation!=='tracking-last-n'&&<p>Przeliczenie autora TrackingAI: <code>{data.formula}</code>. Daty CSV są zapisane jako MM/DD/YYYY. Nie mieszamy testu offline, Mensa Norway ani trybu tekstowego i wizyjnego. Każdy wiersz to pojedynczy test, nie średnia z ostatnich 7 testów.</p>}<p>{data.license}</p><a href={safeUrl(data.sourceUrl)} target="_blank" rel="noreferrer">{data.source} — dokumentacja</a><p>Pełne adresy źródeł, identyfikatory pomiarów i odciski SHA-256 plików wejściowych są w eksporcie JSON.</p></details>
   </>}
   {exporting&&<ExportModal config={config} duration={duration} onClose={()=>setExporting(false)}/>}
 </div>;
}
