import React, {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Check,ChevronRight,Copy,Download,Lightbulb,Pause,Play,Search,Shuffle,X} from 'lucide-react';
import {ideas,matchIdeas,sources} from './catalog.js';
import {drawReel,recordReel} from './render.js';
import {downloadBlob} from './data.js';
import {reelFonts,reelFont} from './reel-style.js';

export function Brand(){return <span className="brand"><span className="brand-bars"><i/><i/><i/></span>plotwist<span className="brand-dot">.</span></span>;}
export function Spark({color='lime'}){return <span className={`spark ${color}`}><svg viewBox="0 0 90 64" aria-hidden="true"><path d="M4 55 L14 47 L24 43 L34 32 L44 37 L54 30 L64 21 L74 20 L86 5"/></svg></span>;}
export function Field({label,children,hint}){return <label className="field"><span className="field-label">{label}</span>{children}{hint&&<small>{hint}</small>}</label>;}
export function FontPicker({value,onChange}){return <Field label="Czcionka rolki"><select aria-label="Czcionka rolki" value={value} onChange={e=>onChange(e.target.value)} style={{fontFamily:reelFont(value)}}>{reelFonts.map(f=><option key={f.id} value={f.id} style={{fontFamily:f.family}}>{f.name}</option>)}</select><span className="font-sample" style={{fontFamily:reelFont(value)}}>Twoja historia. 0123456789</span></Field>;}
export function Modal({title,onClose,children}){
 const ref=useRef();useEffect(()=>{const el=ref.current;el.showModal();return ()=>el.close();},[]);
 return <dialog ref={ref} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose();}}><header><h2>{title}</h2><button className="icon-btn" onClick={onClose} aria-label="Zamknij"><X size={21}/></button></header>{children}</dialog>;
}
export function ReelPreview({config,duration,valid}){
 const ref=useRef(),frame=useRef(),elapsed=useRef(0);const [progress,setProgress]=useState(1),[playing,setPlaying]=useState(false);
 useEffect(()=>{if(valid)drawReel(ref.current,config,progress);},[config,progress,valid]);
 useEffect(()=>{setPlaying(false);setProgress(1);},[config,duration]);
 useEffect(()=>{if(!playing)return;let prev=null;const step=now=>{if(prev!==null)elapsed.current+=(now-prev)/(duration*1000);prev=now;const p=Math.min(elapsed.current,1);setProgress(p);if(p<1)frame.current=requestAnimationFrame(step);else setPlaying(false);};frame.current=requestAnimationFrame(step);return ()=>cancelAnimationFrame(frame.current);},[playing,duration]);
 function toggle(){if(progress>=1){elapsed.current=0;setProgress(0);}else elapsed.current=progress;setPlaying(p=>!p);}
 return <section className="preview" aria-label="Podgląd rolki"><div className="preview-top"><span>PODGLĄD ROLKI</span><span>{config.format} <span className="subtle">·</span> 1080p</span></div><div className="canvas-wrap">{!valid&&<div className="canvas-overlay">Wybierz dane, aby zobaczyć rolkę.</div>}<canvas ref={ref} aria-label={`Podgląd: ${config.title}`} style={{aspectRatio:config.format.replace(':',' / ')}}/></div><div className="player"><button className="play-button" onClick={toggle} disabled={!valid} aria-label={playing?'Zatrzymaj animację':'Odtwórz animację'}>{playing?<Pause size={19} fill="currentColor"/>:<Play size={19} fill="currentColor"/>}</button><input aria-label="Pozycja animacji" type="range" min="0" max="1" step="0.001" value={progress} onChange={e=>{setPlaying(false);setProgress(Number(e.target.value));}}/><span className="time">00:{String(Math.floor(progress*duration)).padStart(2,'0')} <span>/ {duration}s</span></span></div><div className="preview-caption">Twoja historia. Gotowa na mały ekran.</div></section>;
}
export function Inspiration({onPick,onSearch}){const [prompt,setPrompt]=useState('');return <aside className="inspiration"><h2>Następna historia</h2><p className="muted">Dobry wykres zaczyna się od pytania.</p><div className="next-list">{['coffee','adoption','NY.GDP.PCAP.KD'].map((id,index)=>{const idea=ideas.find(i=>i.id===id);return <button className="next-card" key={id} onClick={()=>onPick(idea)}><Spark color={index===1?'purple':index===2?'gray':'lime'}/><span><strong>{idea.title}</strong><small>{index===0?'Małe wybory, wielkie różnice.':index===1?'Kto podbił świat najszybciej?':'Dane, które pokazują większy obraz.'}</small></span><ChevronRight size={17}/></button>;})}</div><button className="text-btn all-ideas" onClick={()=>onSearch('')}>Zobacz wszystkie {ideas.length} pomysłów <ArrowUpRight size={16}/></button><form className="idea-prompt" onSubmit={e=>{e.preventDefault();onSearch(prompt);}}><Lightbulb size={26}/><h3>Masz własny pomysł?</h3><p>Opisz temat. Dobierzemy pasujące historie z biblioteki.</p><textarea aria-label="Twój pomysł" value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Np. jak AI zmienia gospodarkę…"/><button className="secondary" type="submit"><Search size={16}/>Znajdź inspiracje</button><small>Bez API. Dopasowanie do katalogu tematów.</small></form></aside>;}
export function IdeasView({query,setQuery,onPick}){const [category,setCategory]=useState('Wszystkie');const filtered=matchIdeas(query,category);return <div className="library"><div className="page-heading"><div><h1>Znajdź swoją następną historię.</h1><p>Tematy, źródła i pytania, które warto pokazać na wykresie.</p></div><button className="secondary" onClick={()=>onPick(ideas[Math.floor(Math.random()*ideas.length)])}><Shuffle size={17}/>Zaskocz mnie</button></div><div className="search-field"><Search size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Opisz pomysł lub szukaj: AI, Apple, energia…" aria-label="Szukaj pomysłów"/>{query&&<button className="icon-btn" aria-label="Wyczyść wyszukiwanie" onClick={()=>setQuery('')}><X size={18}/></button>}</div><div className="filters">{['Wszystkie','Technologia','Gospodarka','Finanse','Społeczeństwo'].map(c=><button className={category===c?'selected':''} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div><p className="muted result-count">{filtered.length} historii · propozycje z katalogu, bez generowania AI</p><div className="ideas-grid">{filtered.map(i=><button className="idea-card" onClick={()=>onPick(i)} key={i.id}><div className="idea-card-top"><span className={`tag ${i.ready?'ready':''}`}>{i.ready?'Gotowe dane':'Pomysł do opracowania'}</span><ArrowUpRight size={20}/></div><h2>{i.title}</h2><p>{i.hook}</p><div className="idea-meta"><span>{i.category}</span><span>{i.source}</span></div></button>)}</div>{!filtered.length&&<div className="empty"><Lightbulb size={32}/><h2>Jeszcze nie mamy takiej historii.</h2><p>Spróbuj „technologia”, „przychody” lub „inflacja”. W studiu możesz też wkleić własne dane CSV.</p><button className="secondary" onClick={()=>{setQuery('');setCategory('Wszystkie');}}>Pokaż wszystkie pomysły</button></div>}</div>;}
export function SourcesView(){return <div className="library"><div className="page-heading"><div><h1>Duże historie. Dobre źródła.</h1><p>Otwarty świat danych — z jasnym rozróżnieniem, co jest już podłączone.</p></div></div><div className="source-banner"><span className="brand-bars"><i/><i/><i/></span><div><h2>8 wskaźników × 12 krajów i agregatów</h2><p>Pełna dostępna historia World Bank. Zakres zależy od wskaźnika i kraju. Luki nie są uzupełniane sztucznymi wartościami.</p></div></div><div className="sources-list">{sources.map((s,i)=><article className="source-row" key={s.name}><span className="source-number">{String(i+1).padStart(2,'0')}</span><div><h2>{s.name}<span className={`tag ${s.tag==='Podłączone'?'ready':''}`}>{s.tag}</span></h2><p>{s.topics}</p><small>{s.detail}</small></div><a href={s.url} target="_blank" rel="noreferrer" aria-label={`Otwórz ${s.name}`}><ArrowUpRight size={22}/></a></article>)}</div><p className="source-footnote">Publicznie dostępne dane nie zawsze oznaczają dowolną redystrybucję. Zachowaj oznaczenie źródła i sprawdź warunki konkretnego zbioru.</p></div>;}
export function IdeaDetail({idea,onClose,onUse}){const [copied,setCopied]=useState(false);const prompt=`Przygotuj udokumentowany zestaw danych do rolki: „${idea.title}”.\nPytanie: ${idea.hook}\nŹródła: ${idea.source}.\nMetodologia: ${idea.description}\nZweryfikuj źródła pierwotne i podaj bezpośrednie linki, jednostkę, definicję oraz datę pobrania. Nie wymyślaj brakujących danych; zostaw puste komórki. Zwróć CSV z kolumną rok i maksymalnie 3 seriami liczbowymi. Wszystkie serie powinny mieć zgodne jednostki. Nie porównuj MAU, WAU, kont i pobrań jak tej samej miary. Zaproponuj tytuł (do 80 znaków) i narrację na 12 sekund.`;return <Modal title={idea.title} onClose={onClose}><div className="modal-body"><span className="tag">{idea.category}</span><h3>{idea.hook}</h3><p>{idea.description}</p><div className="callout"><strong>Skąd wziąć dane</strong><p>{idea.source}</p></div><p className="muted">{idea.ready?'Ten temat ma gotowe dane lub działający model w studiu.':'To propozycja redakcyjna. Dane nie są jeszcze podłączone. Możesz zebrać je w ChatGPT i wkleić jako CSV.'}</p>{!idea.ready&&<details><summary>Prompt do researchu w ChatGPT</summary><pre className="prompt-text">{prompt}</pre></details>}<div className="modal-actions"><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(prompt);setCopied(true);}catch{setCopied(false);}}}>{copied?<Check size={17}/>:<Copy size={17}/>} {copied?'Skopiowano':'Kopiuj prompt'}</button><button className="primary" onClick={()=>onUse(idea)}>{idea.ready?'Otwórz w studiu':'Przejdź do importu'}<ArrowUpRight size={17}/></button></div></div></Modal>;}
export function ExportModal({config,duration,onClose}){const [status,setStatus]=useState('idle'),[progress,setProgress]=useState(0),[error,setError]=useState('');const abort=useRef();useEffect(()=>()=>abort.current?.abort(),[]);
 async function exportVideo(){setStatus('recording');setError('');abort.current=new AbortController();try{const result=await recordReel(config,duration,setProgress,abort.current.signal);downloadBlob(result.blob,`plotwist-${Date.now()}.${result.extension}`);setStatus('done');}catch(e){setError(e.message);setStatus('idle');}}
 function png(){const canvas=document.createElement('canvas');drawReel(canvas,config,1);canvas.toBlob(blob=>{if(blob)downloadBlob(blob,'plotwist-okladka.png');});}
 return <Modal title="Twoja historia jest gotowa." onClose={onClose}><div className="modal-body"><div className="export-summary"><span><strong>{config.format}</strong>format</span><span><strong>1080p</strong>rozdzielczość</span><span><strong>{duration} s</strong>długość</span></div><p>Wideo bez dźwięku, ze źródłem danych. Eksport WebM (lub MP4, jeśli obsługuje go przeglądarka). Do platform wymagających MP4 może być potrzebna konwersja.</p><p className="muted">Podczas eksportu zostaw tę kartę na wierzchu — animacja nagrywa się w czasie rzeczywistym.</p>{status==='recording'&&<div role="status"><progress max="1" value={progress}/><p>Nagrywanie… {Math.round(progress*100)}%</p></div>}{status==='done'&&<div className="success" role="status"><Check size={20}/>Wideo gotowe. Pobieranie rozpoczęte.</div>}{error&&<p className="error" role="alert">{error}</p>}<div className="modal-actions"><button className="secondary" onClick={png} disabled={status==='recording'}><Download size={17}/>Klatka PNG</button><button className="primary" onClick={exportVideo} disabled={status==='recording'}><Download size={17}/>{status==='recording'?'Eksportowanie…':status==='done'?'Pobierz ponownie':'Pobierz wideo'}</button></div></div></Modal>;
}
