import React,{useEffect,useMemo,useState} from 'react';
import {Download,RotateCcw,Image} from 'lucide-react';
import {Field,ReelPreview} from './components.jsx';
import {useLanguages} from './language-context.js';
import {downloadBlob} from './data.js';
import {graphicConfig,graphicCsv,graphicDefaults,graphicGroups,groupLabel,readGraphicSettings} from './graphic-data.js';
import './graphics.css';
const KEY='plotwist-graphics-v1';
export default function GraphicsStudio({fontId,onLibrary}){
 const {uiLanguage,reelLanguage}=useLanguages(),en=uiLanguage==='en',t=(pl,enText)=>en?enText:pl;
 const [dataset,setDataset]=useState(null),[settings,setSettings]=useState(graphicDefaults),[error,setError]=useState(''),[storageError,setStorageError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{const abort=new AbortController();setError('');fetch('/graphics/fertility-conscription.json',{signal:abort.signal}).then(r=>{if(!r.ok)throw Error(t('Nie udało się wczytać danych.','Could not load data.'));return r.json();}).then(d=>{let draft={};try{draft=JSON.parse(localStorage.getItem(KEY))||{};}catch{}setDataset(d);setSettings(readGraphicSettings(draft,d.rows));}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[retry]);
 useEffect(()=>{if(!dataset)return;try{localStorage.setItem(KEY,JSON.stringify(settings));setStorageError('');}catch{setStorageError(t('Nie można zapisać szkicu w przeglądarce. Pobierz projekt.','Browser draft could not be saved. Download your project.'));}},[dataset,settings]);
 const change=patch=>setSettings(s=>({...s,...patch}));
 const config=useMemo(()=>dataset?{...graphicConfig(dataset,settings,fontId,reelLanguage),onGraphicChange:change}:null,[dataset,settings,fontId,reelLanguage]);
 const groups=useMemo(()=>graphicGroups(config?.graphic.rows||[],settings.statistic),[config,settings.statistic]);
 function downloadProject(){downloadBlob(new Blob([JSON.stringify({type:'plotwist-graphic',version:1,datasetId:dataset.id,settings},null,2)],{type:'application/json'}),'plotwist-grafika.json');}
 async function importProject(e){const f=e.target.files?.[0];e.target.value='';if(!f)return;try{if(f.size>100000)throw Error('Plik jest za duży.');const p=JSON.parse(await f.text());if(p.type!=='plotwist-graphic'||p.version!==1||p.datasetId!==dataset.id)throw Error(t('Nieobsługiwany projekt grafiki.','Unsupported graphic project.'));setSettings(readGraphicSettings(p.settings,dataset.rows));setError('');}catch(e){setError(e.message);}}
 if(!dataset)return <div className="library"><h1>{t('Grafiki','Graphics')}</h1><p role="status">{error||t('Wczytywanie porównania…','Loading comparison…')}</p>{error&&<button className="secondary" onClick={()=>setRetry(x=>x+1)}>{t('Spróbuj ponownie','Retry')}</button>}</div>;
 return <div className="story-page graphic-page">
  <div className="page-heading"><div><span className="story-eyebrow">{t('STUDIO GRAFIK','GRAPHICS STUDIO')}</span><h1>{t('Jedna grafika. Czytelne porównanie.','One graphic. A clear comparison.')}</h1><p>{t('Ten sam edytor, statyczny obraz. Wygląd ustawisz po prawej, elementy również bezpośrednio na podglądzie.','The same editor, a still image. Style it on the right or edit elements directly on the canvas.')}</p></div><button className="secondary" onClick={()=>{try{localStorage.setItem('plotwist-output-mode','image');}catch{}onLibrary();}}><Image size={17}/><span>{t('Grafika z innych danych','Graphic from other data')}</span></button></div>
  <div className="story-workspace reel-workspace"><div className="reel-data-column"><section className="story-controls graphic-controls" aria-label={t('Dane grafiki','Graphic data')}>
   <h2>{t('Pobór a dzietność','Conscription and fertility')}</h2><p>{t('Wszystkie 27 państw UE · 2024. Czynny pobór w czasie pokoju, również selektywny. Sam obowiązek prawny lub dobrowolne szkolenie nie oznaczają czynnego poboru.','All 27 EU countries · 2024. Active peacetime conscription, including selective systems. A legal duty or voluntary training alone does not count.')}</p>
   <Field label={t('Układ porównania','Comparison layout')}><select aria-label={t('Układ porównania','Comparison layout')} value={settings.layout} onChange={e=>change({layout:e.target.value})}><option value="groups">{t('Dwie grupy · słupki krajów','Two groups · country bars')}</option><option value="ranking">{t('Wspólny ranking · kolor grupy','Combined ranking · group colours')}</option><option value="distribution">{t('Kraje i średnia/mediana · punkty','Countries and mean/median · dots')}</option></select></Field>
   <div className="field-pair"><Field label={t('Format grafiki','Image format')}><select aria-label={t('Format grafiki','Image format')} value={settings.format} onChange={e=>change({format:e.target.value})}><option value="4:5">4:5 · 1080 × 1350</option><option value="1:1">1:1 · 1080 × 1080</option><option value="9:16">9:16 · 1080 × 1920</option></select></Field><Field label={t('Podsumowanie grup','Group summary')}><select aria-label={t('Podsumowanie grup','Group summary')} value={settings.statistic} onChange={e=>change({statistic:e.target.value})}><option value="mean">{t('Średnia krajów','Mean of countries')}</option><option value="median">{t('Mediana krajów','Median of countries')}</option></select></Field></div>
   <p className="visual-hint">{t('Każdy kraj ma równą wagę. To nie jest dzietność całej populacji obu grup.','Each country has equal weight. This is not the fertility rate of the pooled populations.')}</p>
   <Field label={t('Tytuł grafiki','Graphic title')}><input value={settings.title} maxLength={300} placeholder={config.title} onChange={e=>change({title:e.target.value})}/></Field>
   <Field label={t('Podtytuł grafiki','Graphic subtitle')}><input value={settings.subtitle} maxLength={300} placeholder={config.subtitle} onChange={e=>change({subtitle:e.target.value})}/></Field>
   <Field label={t('Kolejność krajów','Country order')}><select value={settings.order} onChange={e=>change({order:e.target.value})}><option value="value">{t('Malejąca dzietność','Highest fertility first')}</option><option value="name">{t('Alfabetycznie','Alphabetically')}</option></select></Field>
   <details className="graphic-country-picker" open><summary>{t('Kraje w porównaniu','Countries in comparison')} · {settings.selected.length}/27</summary><div className="story-actions"><button className="text-btn" onClick={()=>change({selected:dataset.rows.map(r=>r.id)})}>{t('Wszystkie','All')}</button><button className="text-btn" onClick={()=>change({selected:[]})}>{t('Odznacz wszystkie','Clear selection')}</button><button className="text-btn" onClick={()=>change({selected:dataset.rows.filter(r=>r.id!=='LVA').map(r=>r.id)})}>{t('Bez Łotwy · nowy pobór w 2024','Exclude Latvia · new draft in 2024')}</button></div>
    {groups.map(group=><fieldset key={group.id}><legend>{groupLabel(group.id,en)} · n = {group.n}</legend>{dataset.rows.filter(r=>r.group===group.id).map(row=><label className="graphic-country" key={row.id}><input type="checkbox" checked={settings.selected.includes(row.id)} onChange={e=>change({selected:e.target.checked?[...settings.selected,row.id]:settings.selected.filter(id=>id!==row.id)})}/><span>{row.name[en?'en':'pl']}</span><span>{row.value.toLocaleString(en?'en-GB':'pl-PL',{maximumFractionDigits:2})}</span></label>)}</fieldset>)}
   </details>
   {settings.selected.length!==27&&<p role="status">{t('Pokazujesz wybrane kraje. Wynik grup zmienia się wraz z wyborem.','Showing selected countries. Group statistics change with your selection.')}</p>}
   <details className="data-details"><summary>{t('Źródła i ograniczenia porównania','Sources and comparison limits')}</summary><p>{dataset.methodology[en?'en':'pl']}</p><p>{t('Klasyfikacja dotyczy 2024 r., nie dzisiejszego prawa. Łotwa wdrożyła pobór w 2024 r.; grafika nie mierzy skutków tej reformy. Późniejsze zmiany, np. w Chorwacji, nie zmieniają grup dla 2024 r.','Classification describes 2024, not current law. Latvia introduced compulsory service in 2024; this chart does not measure the reform’s effects. Later changes, e.g. in Croatia, do not alter the 2024 groups.')}</p><p>World Bank: {dataset.lastUpdated} · {t('Pobrano','Retrieved')}: {dataset.retrievedAt.slice(0,10)}</p>{dataset.sources.map(s=><p key={s.id}><a href={s.url} target="_blank" rel="noreferrer">{s.name}</a></p>)}<a href="/graphics/METHODOLOGY.md" download>{t('Pełna metodologia','Full methodology')}</a></details>
   <div className="story-actions"><button className="secondary" onClick={()=>downloadBlob(new Blob(['\ufeff'+graphicCsv(dataset,settings)],{type:'text/csv;charset=utf-8'}),'dzietnosc-pobor-2024.csv')}><Download size={16}/>CSV</button><a href="/graphics/fertility-conscription.json" download>JSON</a><button className="text-btn" onClick={downloadProject}>{t('Zapisz wybór danych','Save data selection')}</button><label className="text-btn">{t('Wczytaj wybór','Load selection')}<input className="visually-hidden" type="file" accept="application/json,.json" onChange={importProject}/></label></div>
   <p className="visual-hint">{t('Wygląd zapiszesz osobno jako własny motyw w panelu Styl. Plik wyboru danych nie zmienia motywu.','Save appearance separately as a custom theme in Style. A data-selection file does not change your theme.')}</p>
   <button className="text-btn" onClick={()=>setSettings(readGraphicSettings({},dataset.rows))}><RotateCcw size={15}/>{t('Przywróć pełne porównanie','Restore full comparison')}</button>{(error||storageError)&&<p className="error" role="alert">{error||storageError}</p>}
  </section></div><ReelPreview config={config} duration={12} valid={settings.selected.length>0}/></div>
 </div>;
}

