import React,{useEffect,useMemo,useRef,useState} from 'react';
import {ArrowUpRight,Database,Download,FileUp,Plus,Search,Trash2} from 'lucide-react';
import {ExportModal,Field,FontPicker,ReelPreview} from './components.jsx';
import {PresentationPicker,usePresentationSettings} from './Presentation.jsx';
import {VisualEditor} from './VisualSettings.jsx';
import {useLanguages,localeFor} from './language-context.js';
import {translate} from './translations.js';
import {downloadBlob} from './data.js';
import {observationPeriod} from './observation-date.js';
import {buildStoryChart,loadStoryJson,loadStoryTopic,readStoryProject,storyColors,storyCsv,storyDefaults,storyProject,storyRange,storyRows,topicSelection} from './story-data.js';
import './stories.css';

const countryAliases={Poland:'Polska POL', 'United States':'USA Stany Zjednoczone', China:'Chiny CHN', Germany:'Niemcy DEU', 'United Kingdom':'Wielka Brytania GBR', Japan:'Japonia JPN', France:'Francja FRA', India:'Indie IND', 'South Korea':'Korea KOR', Brazil:'Brazylia BRA', World:'Świat WLD', Norway:'Norwegia NOR', Sweden:'Szwecja SWE', Italy:'Włochy ITA', Spain:'Hiszpania ESP'};
const draftKey='plotwist-story-project-v1';
const fold=s=>s.toLocaleLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replaceAll('ł','l');
export default function StoryStudio({initialTopic,fontId,onFontChange}){
 const {uiLanguage,reelLanguage}=useLanguages(),t=(pl,en)=>uiLanguage==='en'?en:pl;
 const {setAxisScale}=usePresentationSettings();
 const [manifest,setManifest]=useState(null),[settings,setSettings]=useState(storyDefaults),[loaded,setLoaded]=useState({});
 const [initialized,setInitialized]=useState(false),[busy,setBusy]=useState(false),[loadError,setLoadError]=useState(''),[retry,setRetry]=useState(0);
 const [query,setQuery]=useState(''),[compatible,setCompatible]=useState(false),[tab,setTab]=useState('data'),[page,setPage]=useState(0),[tableSeries,setTableSeries]=useState('all');
 const [exporting,setExporting]=useState(false),[notice,setNotice]=useState(''),[storageError,setStorageError]=useState('');
 const fileRef=useRef();
 const set=(key,value)=>setSettings(s=>({...s,[key]:value}));
 useEffect(()=>{let active=true;setLoadError('');loadStoryJson('/stories/manifest.json').then(m=>{if(active)setManifest(m);}).catch(e=>{if(active)setLoadError(e.message);});return()=>{active=false;};},[retry]);
 useEffect(()=>{
  if(!manifest||initialized)return;
  const topic=manifest.topics.find(t=>t.id===initialTopic)||manifest.topics.find(t=>t.id==='apple');
  let next={...storyDefaults,topic:topic.id,selected:topicSelection(topic),mode:topic.defaultMode,chart:topic.defaultChart};
  if(!initialTopic)try{const saved=JSON.parse(localStorage.getItem(draftKey));if(saved)next=readStoryProject(saved,manifest);}catch{/* A deleted dataset or old draft falls back to a known topic. */}
  if(initialTopic&&topic.defaultAxisScale)setAxisScale(topic.defaultAxisScale);
  setSettings(next);setInitialized(true);
 },[manifest,initialTopic,initialized]);
 useEffect(()=>{if(!initialized)return;try{localStorage.setItem(draftKey,JSON.stringify(storyProject(settings,manifest.builtAt)));setStorageError('');}catch{setStorageError(t('Nie udało się zapisać szkicu w przeglądarce. Pobierz projekt JSON.','Browser storage is unavailable. Download the project JSON.'));}},[initialized,settings,manifest]);
 const metadata=useMemo(()=>new Map(manifest?.series.map(s=>[s.id,s])||[]),[manifest]);
 const needed=useMemo(()=>[...new Set(settings.selected.map(s=>metadata.get(s.id)?.topicId).filter(Boolean))].sort().join('|'),[settings.selected,metadata]);
 useEffect(()=>{
  if(!initialized)return;
  if(!needed){setBusy(false);setLoadError('');return;}
  let active=true;setBusy(true);setLoadError('');
  Promise.all(needed.split('|').map(loadStoryTopic)).then(data=>{if(active)setLoaded(old=>({...old,...Object.fromEntries(data.map(d=>[d.topic.id,d]))}));}).catch(e=>{if(active)setLoadError(e.message);}).finally(()=>{if(active)setBusy(false);});
  return()=>{active=false;};
 },[needed,initialized,retry]);
 const selectedData=useMemo(()=>settings.selected.map(item=>loaded[metadata.get(item.id)?.topicId]?.series.find(s=>s.id===item.id)).filter(Boolean),[settings.selected,loaded,metadata]);
 const complete=selectedData.length===settings.selected.length;
 const range=useMemo(()=>storyRange(selectedData),[selectedData]);
 const result=useMemo(()=>{if(!complete)return {series:[],bases:[],error:''};try{return {...buildStoryChart(selectedData,settings),error:''};}catch(e){return {series:[],bases:[],error:e.message};}},[selectedData,settings,complete]);
 const rows=useMemo(()=>storyRows(selectedData,settings.start,settings.end),[selectedData,settings.start,settings.end]);
 const filteredRows=useMemo(()=>tableSeries==='all'?rows:rows.filter(p=>p.seriesId===tableSeries),[rows,tableSeries]);
 useEffect(()=>{setPage(0);},[rows,tableSeries]);
 const topic=manifest?.topics.find(t=>t.id===settings.topic);
 const available=useMemo(()=>{
  const terms=fold(query).split(/\s+/).filter(Boolean),unit=metadata.get(settings.selected[0]?.id)?.unitKey;
  return (manifest?.series||[]).filter(s=>(settings.topic==='all'||s.topicId===settings.topic)&&(!compatible||!unit||s.unitKey===unit)&&terms.every(q=>fold(`${s.name} ${s.entity} ${countryAliases[s.entity]||''} ${s.unit} ${s.metric} ${s.notes}`).includes(q)));
 },[manifest,settings.topic,settings.selected,query,compatible,metadata]);
 const [candidateLimit,setCandidateLimit]=useState(8);
 useEffect(()=>setCandidateLimit(8),[query,settings.topic,compatible]);
 const sourcesById=useMemo(()=>new Map(manifest?.sources.map(s=>[s.id,s])||[]),[manifest]);
 const usedSources=useMemo(()=>[...new Set(selectedData.flatMap(s=>s.sourceIds))].map(id=>sourcesById.get(id)).filter(Boolean),[selectedData,sourcesById]);
 const usedTopics=useMemo(()=>[...new Set(selectedData.map(s=>s.topicId))].map(id=>manifest?.topics.find(t=>t.id===id)).filter(Boolean),[selectedData,manifest]);
 const autoTitle=usedTopics.length===1?usedTopics[0].title:t('Wybrane historie','Selected histories');
 const config=useMemo(()=>{
  const en=reelLanguage==='en',sourceNames=[...new Set(usedSources.map(s=>s.shortName||s.name.split(' · ')[0].replace(/Form (10-K|20-F).*/,'')))];
  const singleTopic=usedTopics.length===1?usedTopics[0]:null,summary=singleTopic?.dateMeaning==='publication';
  const note=singleTopic?.reelNote?.[reelLanguage]||(en?'historical observations':'obserwacje historyczne');
  return {series:result.series,title:settings.title||autoTitle,titleIsCustom:!!settings.title,subtitle:`${translate(result.unit||'',reelLanguage)} · ${note}${settings.mode==='index'?(en?' · own start = 100':' · własny początek = 100'):''}`,subtitleIsCustom:true,unit:result.unit||'',unitIsCustom:false,source:`${en?'Source':'Źródło'}: ${sourceNames.join(' / ')}${en?' · full methodology in dataset':' · metodologia w zbiorze'}`,sourceIsCustom:true,xType:'date',showObservationDates:!summary,dateLabel:summary?(en?'Report · 22 Sep 2026':'Raport · 22.09.2026'):undefined,datePrecision:result.datePrecision,format:settings.format,duration:settings.duration,fontId,chart:settings.chart,theme:'dark',compactTitle:true};
 },[result,settings.title,settings.mode,settings.chart,settings.format,settings.duration,autoTitle,fontId,usedSources,usedTopics,reelLanguage]);
 const valid=initialized&&complete&&!busy&&!loadError&&!result.error&&result.series.length>0;
 const number=v=>v===null?'—':v.toLocaleString(localeFor(uiLanguage),v!==0&&Math.abs(v)<1?{maximumSignificantDigits:6}:{maximumFractionDigits:6});
 function add(s){setSettings(current=>current.selected.length>=6||current.selected.some(item=>item.id===s.id)?current:{...current,selected:[...current.selected,{id:s.id,color:storyColors.find(color=>!current.selected.some(item=>item.color===color))||storyColors[current.selected.length],label:''}]});}
 function remove(id){setSettings(current=>({...current,selected:current.selected.filter(item=>item.id!==id)}));setTableSeries('all');}
 function preset(){if(!topic?.defaults.length)return;setSettings(s=>({...s,selected:topicSelection(topic),start:'',end:'',mode:topic.defaultMode,title:'',chart:topic.defaultChart}));if(topic.defaultAxisScale)setAxisScale(topic.defaultAxisScale);setNotice('');}
 function download(content,name,type='application/json'){downloadBlob(new Blob([type==='application/json'?JSON.stringify(content,null,2):content],{type}),name);}
 async function importProject(event){
  const file=event.target.files?.[0];event.target.value='';if(!file)return;
  try{if(file.size>200000)throw Error(t('Plik projektu jest za duży. Wczytaj wariant, nie cały dataset.','Project file is too large. Load a saved variant, not a dataset.'));const value=JSON.parse(await file.text());setSettings(readStoryProject(value,manifest));setTableSeries('all');setNotice(value.snapshotBuiltAt===manifest.builtAt?t('Wczytano wariant.','Variant loaded.'):t('Wczytano wariant. Dane pochodzą z aktualnego snapshotu biblioteki.','Variant loaded using the current library snapshot.'));}catch(e){setNotice(e.message);}
 }
 if(!manifest||!initialized)return <div className="library"><h1>{t('Biblioteka danych','Data library')}</h1><p role="status">{loadError||t('Wczytywanie katalogu…','Loading catalogue…')}</p>{loadError&&<button className="secondary" onClick={()=>setRetry(x=>x+1)}>{t('Spróbuj ponownie','Retry')}</button>}</div>;
 return <div className="story-page">
  <div className="page-heading"><div><span className="story-eyebrow">{t('BIBLIOTEKA → WŁASNA HISTORIA','LIBRARY → YOUR STORY')}</span><h1>{t('Dane są. Teraz Twoja perspektywa.','The data is here. Make it your story.')}</h1><p>{t('Wybierz serie, ustaw zakres i ułóż własny wariant wizualizacji.','Choose series, set a date range and compose your own visualization.')}</p></div><a className="secondary" href="/stories/plotwist-story-datasets.zip" download><Download size={16}/>{t('Cała biblioteka ZIP','Full library ZIP')}</a></div>
  <div className="story-stats"><span><strong>{manifest.topics.filter(t=>t.seriesCount).length}</strong>{t('tematów z danymi','topics with data')}</span><span><strong>{number(manifest.series.length)}</strong>{t('serii do wyboru','available series')}</span><span><strong>{number(manifest.topics.reduce((n,t)=>n+t.count,0))}</strong>{t('obserwacji','observations')}</span><small>{t('Snapshot','Snapshot')} {new Date(manifest.builtAt).toLocaleDateString(localeFor(uiLanguage))}<br/>{t('Zakres i kompletność zależą od źródła.','Coverage and completeness vary by source.')}</small></div>
  <div className="story-workspace"><section className="story-controls" aria-label={t('Kompozytor danych','Data composer')}>
   <div className="tabs">{[['data',t('Dane','Data')],['style',t('Wygląd','Style')]].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)} aria-pressed={tab===id}>{label}</button>)}</div>
   {tab==='data'?<>
    <section className="story-browser"><Field label={t('1. Odkryj temat','1. Explore a topic')}><select aria-label={t('Temat danych','Data topic')} value={settings.topic} onChange={e=>{set('topic',e.target.value);setQuery('');}}><option value="all">{t('Wszystkie tematy','All topics')}</option>{manifest.topics.filter(t=>t.seriesCount).map(t=><option key={t.id} value={t.id}>{t.title} · {t.seriesCount}</option>)}</select></Field>
     {topic&&<><div className="story-topic-heading"><span className={`tag ${topic.status==='ready'?'ready':''}`}>{topic.status==='partial'?t('Częściowy zakres','Partial coverage'):t('Dane opracowane','Data prepared')}</span><span>{topic.start?.slice(0,4)}–{topic.end?.slice(0,4)}</span></div><p className="story-note" translate="no">{topic.note}</p><div className="story-actions"><button className="secondary" onClick={preset}><Database size={15}/>{t('Wczytaj zestaw tematu','Load topic preset')}</button><a href={`/stories/${encodeURIComponent(topic.id)}.csv`} download>CSV</a><a href={`/stories/${encodeURIComponent(topic.id)}.json`} download>JSON</a></div></>}
     {topic?.variants&&<details className="story-note"><summary>{t('Jakie historie można z tego ułożyć?','What stories can you tell with this?')}</summary>{topic.variants.map(v=><p key={v} translate="no">{v}</p>)}</details>}
     {topic?.methodologyPath&&<a className="story-note" href={topic.methodologyPath} download>{t('Pobierz metodologię i pomysły na rolki','Download methodology and reel ideas')}</a>}
     <div className="search-field"><Search size={17}/><input aria-label={t('Szukaj serii danych','Search data series')} value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('Szukaj kraju, firmy lub wskaźnika…','Search a country, company or metric…')}/></div>
     <label className="story-check"><input type="checkbox" checked={compatible} onChange={e=>setCompatible(e.target.checked)}/>{t('Tylko jednostka zgodna z pierwszą serią','Only units compatible with the first series')}</label>
     <div className="story-candidates">{available.slice(0,candidateLimit).map(s=>{const chosen=settings.selected.some(x=>x.id===s.id);return <div className="story-candidate" key={s.id}><div><strong translate="no">{s.name}</strong><small translate="no">{s.unit} · {s.start.slice(0,4)}–{s.end.slice(0,4)} · {s.count} {t('obserwacji','observations')}</small></div><button type="button" className={`story-series-action${chosen?' is-selected':''}`} disabled={!chosen&&settings.selected.length>=6} onClick={()=>chosen?remove(s.id):add(s)} aria-label={`${chosen?t('Usuń','Remove'):t('Dodaj','Add')} ${s.name}`} title={!chosen&&settings.selected.length>=6?t('Maksymalnie 6 serii. Usuń jedną, aby dodać inną.','Maximum 6 series. Remove one to add another.'):undefined}>{chosen?<Trash2 size={15}/>:<Plus size={16}/>}<span>{chosen?t('Usuń','Remove'):t('Dodaj','Add')}</span></button></div>;})}</div>
     <div className="story-result-count"><small>{available.length} {t('pasujących serii','matching series')}</small>{candidateLimit<available.length&&<button className="text-btn" onClick={()=>setCandidateLimit(n=>n+20)}>{t('Pokaż kolejne','Show more')}</button>}</div>
    </section>
    <section className="story-selection"><h2>{t('2. Skomponuj wykres','2. Compose a chart')}<span>{settings.selected.length}/6</span></h2>
     {settings.selected.map((item,i)=>{const s=metadata.get(item.id),base=result.bases?.find(b=>b.id===item.id);if(!s)return null;return <div className="story-selected" key={item.id} style={{borderLeftColor:item.color}}><div className="story-selected-top"><input type="color" value={item.color} aria-label={`${t('Kolor','Color')} ${s.name}`} onChange={e=>set('selected',settings.selected.map(x=>x.id===item.id?{...x,color:e.target.value}:x))}/><span translate="no">{s.name}</span><button className="icon-btn" aria-label={`${t('Usuń','Remove')} ${s.name}`} onClick={()=>remove(item.id)}><Trash2 size={15}/></button></div><input className="story-label" aria-label={`${t('Nazwa na rolce','Reel label')} ${i+1}`} placeholder={t('Własna krótka nazwa na rolce (opcjonalnie)','Short reel label (optional)')} maxLength={80} value={item.label} onChange={e=>set('selected',settings.selected.map(x=>x.id===item.id?{...x,label:e.target.value}:x))}/><small translate="no">{s.unit} · {s.start} → {s.end}</small>{settings.mode==='index'&&base&&<small translate="no">100 = {number(base.value)} {base.unit} · {observationPeriod(base)}</small>}<details><summary>{t('Definicja i źródła','Definition and sources')}</summary><p translate="no">{s.notes||s.metric}</p>{s.sourceIds.map(id=>{const source=sourcesById.get(id);return source&&<a key={id} href={source.reportUrl||source.url} target="_blank" rel="noreferrer">{source.name}<ArrowUpRight size={12}/></a>;})}</details></div>;})}
     <Field label={t('Porównanie wartości','Value comparison')}><select aria-label={t('Porównanie wartości','Value comparison')} value={settings.mode} onChange={e=>set('mode',e.target.value)}><option value="native">{t('Oryginalne wartości · zgodne jednostki','Original values · compatible units')}</option><option value="index">{t('Indeks 100 · tempo zmian','Index 100 · relative change')}</option></select><small>{settings.mode==='index'?t('Każda seria: pierwsza dostępna wartość w zakresie = 100. Daty bazowe widać powyżej; mogą się różnić. To nie porównanie poziomów.','Each series starts at 100 at its first observation in the range. Base dates are shown above and may differ. This compares change, not levels.'):t('Różnych walut, MAU/WAU i przepływów rocznych/kwartalnych nie łączymy na jednej osi wartości.','Different currencies, MAU/WAU and annual/quarterly flows require separate value axes.')}</small></Field>
     <div className="field-pair"><Field label={t('Od','From')}><input type="date" aria-label={t('Dane od','Data from')} value={settings.start||range.start} onChange={e=>set('start',e.target.value)}/></Field><Field label={t('Do','To')}><input type="date" aria-label={t('Dane do','Data to')} value={settings.end||range.end} onChange={e=>set('end',e.target.value)}/></Field></div><div className="story-actions"><button className="text-btn" onClick={()=>setSettings(s=>({...s,start:'',end:''}))}>{t('Pełna historia','Full history')}</button><button className="text-btn" disabled={!range.commonStart||range.commonStart>range.commonEnd} onClick={()=>setSettings(s=>({...s,start:range.commonStart,end:range.commonEnd}))}>{t('Wspólny zakres','Overlapping range')}</button></div>
    </section>
    <PresentationPicker config={config} value={settings.chart} onChange={v=>set('chart',v)}/>
    {result.hasSingle&&['line','area'].includes(settings.chart)&&<p className="story-note">{t('Co najmniej jedna seria ma tylko jeden pomiar. Wybierz karty lub słupki, aby go zobaczyć.','At least one series contains a single observation. Use cards or bars to display it.')}</p>}
    <Field label={t('Tytuł rolki','Reel title')}><textarea value={settings.title} placeholder={translate(autoTitle,reelLanguage)} maxLength={80} onChange={e=>set('title',e.target.value)}/></Field><div className="field-pair"><Field label={t('Format','Format')}><select value={settings.format} onChange={e=>set('format',e.target.value)}>{['9:16','1:1','4:5'].map(v=><option key={v}>{v}</option>)}</select></Field><Field label={t('Długość','Duration')}><select value={settings.duration} onChange={e=>set('duration',Number(e.target.value))}>{[6,12,20,30].map(v=><option key={v} value={v}>{v} s</option>)}</select></Field></div>
   </>:<><FontPicker value={fontId} onChange={onFontChange}/><VisualEditor/></>}
   {busy&&<p role="status" className="helper">{t('Wczytywanie obserwacji…','Loading observations…')}</p>}{loadError&&<p role="alert" className="error">{translate(loadError,uiLanguage)} <button onClick={()=>setRetry(n=>n+1)}>{t('Ponów','Retry')}</button></p>}{result.error&&<p role="alert" className="error">{translate(result.error,uiLanguage)}</p>}
   <div className="story-project"><button className="primary" disabled={!valid} onClick={()=>setExporting(true)}><Download size={16}/>{t('Eksportuj wideo','Export video')}</button><button className="secondary" disabled={!settings.selected.length} onClick={()=>download(storyProject(settings,manifest.builtAt),'plotwist-wariant.json')}><Download size={15}/>{t('Zapisz wariant','Save variant')}</button><button className="secondary" onClick={()=>fileRef.current?.click()}><FileUp size={15}/>{t('Wczytaj wariant','Load variant')}</button><input ref={fileRef} hidden type="file" accept=".json,application/json" onChange={importProject}/><small>{storageError||t('Szkic zapisuje się automatycznie w tej przeglądarce. Plik wariantu przechowuje wybór danych i ustawienia tego panelu; wygląd i media mają osobny wspólny szkic.','The draft is saved in this browser. Variant files store this panel’s data selection and settings; appearance and media use a separate shared draft.')}</small>{notice&&<p role="status">{notice}</p>}</div>
  </section><ReelPreview config={config} duration={settings.duration} valid={valid}/></div>
  <section className="story-observations"><div className="page-heading"><div><h2>{t('Obserwacje, chronologicznie.','Observations, in chronological order.')}</h2><p>{t('Oryginalne wartości przed indeksowaniem. Puste komórki oznaczają brak danych.','Original values before indexing. Empty values mean missing data.')}</p></div><div className="story-actions"><button className="secondary" disabled={!rows.length} onClick={()=>download(storyCsv(rows,usedSources),'plotwist-wybrane-dane.csv','text/csv;charset=utf-8')}>CSV</button><button className="secondary" disabled={!rows.length} onClick={()=>download({schemaVersion:1,builtAt:manifest.builtAt,settings,series:selectedData.map(s=>({...s,points:s.points.filter(p=>(!settings.start||p.date>=settings.start)&&(!settings.end||p.date<=settings.end))})),sources:usedSources},'plotwist-wybrane-dane.json')}>JSON</button></div></div>
   <Field label={t('Seria w tabeli','Table series')}><select value={tableSeries} onChange={e=>setTableSeries(e.target.value)}><option value="all">{t('Wszystkie wybrane','All selected')}</option>{selectedData.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><div className="story-table-wrap"><table><thead><tr>{[t('Okres','Period'),t('Seria','Series'),t('Wartość','Value'),t('Jednostka','Unit'),t('Źródło','Source')].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{filteredRows.slice(page*25,(page+1)*25).map(p=><tr key={p.seriesId+p.date}><td translate="no">{observationPeriod(p,uiLanguage)}<small>{p.datePrecision==='fiscal-year'?p.date:''}</small></td><td translate="no">{p.seriesName}{p.model&&<small>{p.model}</small>}{p.vehicle&&<small>{p.vehicle}</small>}</td><td translate="no">{p.valueQualifier==='approximately'?'≈ ':p.valueQualifier||''}{number(p.value)}</td><td translate="no">{p.unit}</td><td>{sourcesById.get(p.sourceId)&&<a href={sourcesById.get(p.sourceId).url} target="_blank" rel="noreferrer">{sourcesById.get(p.sourceId).shortName||sourcesById.get(p.sourceId).name}<ArrowUpRight size={12}/></a>}</td></tr>)}</tbody></table></div><div className="pagination"><span>{filteredRows.length} {t('wierszy · od najstarszych','rows · oldest first')} · {t('strona','page')} {page+1}/{Math.max(1,Math.ceil(filteredRows.length/25))}</span><div><button className="secondary" disabled={page===0} onClick={()=>setPage(p=>p-1)}>{t('Poprzednia','Previous')}</button><button className="secondary" disabled={(page+1)*25>=filteredRows.length} onClick={()=>setPage(p=>p+1)}>{t('Następna','Next')}</button></div></div>
   <details className="story-methodology"><summary>{t('Zakres, źródła i interpretacja','Coverage, sources and interpretation')}</summary><p>{t('Znaczenie dat opisuje definicja serii: okres pomiaru, premiera modelu lub publikacja zestawienia. Rok/kwartał/miesiąc zachowuje dokładność źródła; daty końca okresu służą porządkowaniu. Między pomiarami podpis pokazuje ostatnią znaną wartość. Animacja linii nie tworzy pomiarów. Progi oznaczamy >, wartości przybliżone ≈.','Series definitions specify whether dates mean measurement periods, model releases or publication of a comparison. Year, quarter and month retain the source precision; period-end dates are sorting anchors. Between observations labels show the last known value. Line animation does not create measurements. > denotes a threshold and ≈ an approximate value.')}</p>{usedTopics.map(t=><p key={t.id} translate="no"><strong>{t.title}.</strong> {t.note}</p>)}<a href="/stories/README.md" download>{t('Opis formatu danych','Data format documentation')}</a> · <a href="/stories/quality-report.json" download>{t('Raport zakresu i kontroli danych','Coverage and data checks')}</a></details>
  </section>{exporting&&<ExportModal config={config} duration={settings.duration} onClose={()=>setExporting(false)}/>}
 </div>;
}
